### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by shailen-naidoo** [kiaking/vuex-ideas#6]
Hey, I like the concept of this repo. Let me know if you need help or need some feedback

**Comment by kiaking** [comment]
Hi! Thanks for checking in! Currently this is just an idea, and it's still wondering around. Though if you have any good ideas, I'm willing to hear it 👍

**Comment by shailen-naidoo** [comment]
Thanks @kiaking Looking forward to seeing what's happening
